### ISSUE TITLE
Distribution-specific patch application

### ISSUE THREAD

**Issue by ethangreen-dev** [ethangreen-dev/lovely-injector#205]
With Gamepass support slated for the next release it would be ideal to have some way for patches to _only_ fire for a specified distribution paltform. This could be specified by a `distributions` field:

```toml
# Back:init()
[[patches]]
[patches.pattern]
target = 'back.lua'
pattern = "if not selected_back then selected_back = G.P_CENTERS.b_red end"
position = 'after'
match_indent = true
payload = "self.atlas = selected_back.unlocked and selected_back.atlas or nil"
distributions = ["gamepass"]
```

- [ ] Distribution detection in `lovely-core`
- [ ] Add `distributions` field to patch format
- [ ] Add filter step to patch loader to invalidate patches who target other distributions
